### PR TITLE
New: Group hint reports with the same message text

### LINKED ISSUE #2970: Combine hint reports for same issue
Right now we can get the same "hint" multiple times but for different resources, different parts of the code, etc.
This isn't a great experience and can cause the user to miss another hint  after too much repetition. We should combine then (maybe in a nested details/summary?). This applies to the browser extension and the html formatter, although probably the browser has higher priority (IMO).

image

### PR DESCRIPTION
**Pull request by antross**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

Also update layout of related controls to prefer controlling spacing
from parent controls instead of children. This makes child controls
easier to re-use without breaking layout.

- - - - - - - - - -

Fix #2970

### CODE REVIEW

**Comment by antross** [comment]
Pre-built bundles for testing:
* [Chromium webhint-0.1.0.zip](https://github.com/webhintio/hint/files/3628498/webhint-0.1.0.zip)
* [Firefox webhint-0.1.0.zip](https://github.com/webhintio/hint/files/3628499/webhint-0.1.0.zip)

Screenshot:
image

**Comment by antross** [comment]
Updated test packages with revised summary behavior:
* [Chromium webhint-0.1.0.zip](https://github.com/webhintio/hint/files/3628644/webhint-0.1.0.zip)
* [Firefox webhint-0.1.0.zip](https://github.com/webhintio/hint/files/3628645/webhint-0.1.0.zip)

Screenshot:

image

**Comment by sarvaje** [comment]
I think it continue being a little bit confusing having a 2 for accessibility, and then there are 3 hints for it. I know that is 2 "rules" that are "failing", but it can be a little bit confusing.

**Comment by antross** [comment]
> I think it continue being a little bit confusing having a 2 for accessibility, and then there are 3 hints for it. I know that is 2 "rules" that are "failing", but it can be a little bit confusing.

Fair point. @hxlnt and @molant what do you think? Should we leave this as-is for now, or consider making the count align with the sum of the "hints: x" summaries for each hint (which could be quite a bit larger)?

**Comment by molant** [comment]
I'd leave as it is, I think it's already an improvement compared to what we have right now. We can maybe brainstorm a bit more until tomorrow noon and if we haven't come up with something better just merge it so we can ship v1.

Some ideas: remove the word "Hints:" from the results and just put the number or think of a better word (Issues?)


________________________________

**Comment by molant** [comment]
What about something like the following:

image

1. We keep the colored dots (we will have to add the passed one, I just scanned a website with 0 issues in PWA and there wasn't any color)
1. Remove the number of passed hints from there
1. In the title of the category tell how many hints have found issues (current copy is an example, happy to change it to whatever)
1. Replace `Hints:` with `Issues:`. This will be also more consistent with the current `No issues` message in the same place

Thoughts?

**Comment by antross** [comment]
@molant How about we move this to an issue if we want to keep discussing refining the display since we've already agreed on what we're doing for this PR?

**Comment by molant** [comment]
OK. Didn't know we have con sensus for this PR.


________________________________

**Pull request merged**
