### PR TITLE
Fix: Consider base tag when resolving URLs

### LINKED ISSUE #2465: [Bug] Correctly support `<base>` in all connectors [3]
# 🐛 Bug report

We have a few issues with `<base>` not working properly. This can be verified in the `hint-sri` and `hint-no-broken-links`.

* `base` can be relative and our current code path with `new URL` does not accept it and fails. We should use the following code or something similar to fix that (currently available in https://github.com/webhintio/hint/pull/2468/commits/c3c8e2392ff62cf2c6f40eb822f785f95802773c but should be added to `no-broken-links` as well):
```ts
const createResourceURL = (resource: string) => {
    const targetURL = evt.resource;
    const pageDOM = this.context.pageDOM!;
    const baseTags = pageDOM.querySelectorAll('base');
    const hrefAttribute = (baseTags.length === 0) ? '' : (baseTags[0].getAttribute('href') || '');
    const baseURL = new URL(hrefAttribute, targetURL);

    /**
        * `new URL(path, base)` only uses `base.origin` to create
        * the new URL. E.g.:
        *
        * ```ts
        * const resourceURL = new URL('/style.css', 'https://localhost/nested/');
        *
        * resourceURL.href === 'https://localhost/style.css';
        * ```
        * What is needed is `https://localhost/nested/style.css`
        *
        * To solve this we use `path.join` with `base.pathname`
        * and we use the result to create a new `URL`.
        */
    const pathname = join(baseURL.pathname, resource);
    const resourceURL = new URL(pathname, baseURL);

    debug(`calculated "resourceURL": ${resourceURL}`);

    return resourceURL;
};
``` 
* `resourceLoader` for jsdom is not taking into account `base` correctly. Don't know if it's because we pass a `_finalHref` or what. Need to investigate a bit more. Chrome seems to be reporting the right downloaded URL.
* not sure that `getElementByUrl` is going to work correctly with `base`. We might be passing a different URL than expected. Need to double check this.

-------------------------------------------------

**OLD REPORT**

## Description

Hi 👋,
I noticed that the sri hint doesn't resolve URLs with the base href anymore in case it is used. Some time ago I submitted a pull request to fix this. But there seems to be no trace of those changes anymore in the current code.

Here is a link to one of the commits from last August:
https://github.com/webhintio/hint/commit/4817bc884ddd958cfbaa886ddc3ac6103e3d8040

## Environment

* __`hint` version:__ v5.0.1
* __`Node.js` version:__ v11.15.0
* __`OS`:__ OS X
* __URL for which webhint failed:__ https://chrisguttandin.github.io/angular-meetup-berlin-april-2019/slides/1

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
{
    "browserslist": [
        "last 2 Chrome versions",
        "last 2 Edge versions",
        "last 2 Firefox versions",
        "last 2 Opera versions",
        "last 2 Safari versions"
    ],
    "connector": {
        "name": "chrome",
        "options": {
            "waitFor": 1000
        }
    },
    "formatters": [
        "stylish"
    ],
    "hints": {
        "sri": [
            "error",
            {
                "originCriteria": "all"
            }
        ]
    },
    "hintsTimeout": 120000
}


```

</details>

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
https://chrisguttandin.github.io/web-audio-conference-2016/slides/1
line 0  col 888   Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/styles.0d342b82d21c340a7319.css doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-91mdN8qjIiXZ0GEwH8MUuEbd7RCwdwesDZ0pHnF5f4OZCu7zvmBokMYjKbpxZ17X    sri
line 0  col 1065  Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/4.a0a92c5a6ca72d866ceb.js doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-25mC50a1kqLhhBEcS+mw4DIBVoluiE22vMKqM2Go+auygPWdE+k2F4pZhyyFp1T5          sri
line 0  col 5244  Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/polyfills.61ddf36ababb35d368c0.js doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-+N7evcl7zrc6o9kMNnhuSkeAgOTW8X1IJ9QNoUeFg1Nk2F9iePwtyeN23Xmrfvl8  sri
line 0  col 5440  Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/scripts.2e1ce7e02614f3c7a0cf.js doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-yI6gqSjsIyAXA7wFcWkQ4wOL/tjbFiuFsNpCjJ8HTMnMqjIRVSzn3rALqetuHCfy    sri
line 0  col 5634  Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/main.d5fd304e58c763fb812c.js doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-hoMI7obu/2kkxYGPqjXQxSxWT6qgUjNl5eks+Jla4W/FiWlpmAS/TeKQTHc7BdVa       sri
✖ Found 5 errors and 0 warnings

✖ Found a total of 5 errors and 0 warnings
```

</details>

It fails because it resolves the URLs incorrectly and downloads a different (the 404.html file) file instead.

### PR DESCRIPTION
**Pull request by chrisguttandin**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

## Short description of the change(s)

Hi @molant, this is meant to fix #2465 at some point but I think I need some guidance first.

For now I more or less copy/pasted a method out of the `no-broken-links` hint. The function is originally defined here: https://github.com/webhintio/hint/blob/master/packages/hint-no-broken-links/src/hint.ts#L162

Do you think it makes sense to move it to a central place? Also it looks a bit misplaced in the `sri` hint as this is written as a class with methods and properties whereas the `no-broken-links` hint defines all functionality within the constructor.

For some reason I had to change the type definitions of the code inside the function body. Do you know why that was necessary?

I also added a first test just to prove it's working. I guess I need to add other tests as well later on.

Thanks for your help.

### CODE REVIEW

**Comment by molant** [comment]
So the new test in sri is failing and `no-broken-links` keeps failing on linux :(

```
Received results is [
    {
      "category": "security",
      "hintId": "sri",
      "location": {
        "column": 30,
        "line": 3
      },
      "message": "The hash in the \"integrity\" attribute in resource https://localhost:9550/styles.css doesn't match the received payload.\nExpected: sha512-fEGRK4NdBb0dHyzU2SV6UwUiRE8Ph/+PcMXLu9/X+RMG2SvY3Rlhs9buP8OqCH5tvyYqqro/v80+z5QhS/UMyA==\nActual:   sha512-qC6bbhWZ7Rr0ACjhjfJpavLUm3oAUCbcheJUYNSb4DKASapgeWGLZBGXLTsoaASFg1VeCzTKs1QIMkWaL1ewsA==",
      "resource": "https://localhost:9550/",
      "severity": 2,
      "sourceCode": "<link rel=\"stylesheet\" href=\"/styles.css\" integrity=\"sha512-qC6bbhWZ7Rr0ACjhjfJpavLUm3oAUCbcheJUYNSb4DKASapgeWGLZBGXLTsoaASFg1VeCzTKs1QIMkWaL1ewsA==\">"
    }
  ]
``` 

I'm looking into why the hash is different than the expected one because 🤔

**Comment by molant** [comment]
This is actually more complicated than expected. Looks like:

* `new URL` does not accept relative URL (I have that part fixed)
* `resourceLoader` for jsdom is not taking into account `base` correctly
* not sure that `getElementByUrl` is going to work correctly with `base`

I'll repurpose #2465 to make sure everything is working as expected but will take a bit more as the work is more than anticipated and need to fixing a couple things in the release script first :(

**Comment by sarvaje** [comment]
Closing this PR in favor of #2596

**Comment by sarvaje** [comment]
Thank you @chrisguttandin for this PR!!

We are moving the URL calculation to the connectors, so the hints don't need to much code to get the final URL.

**Comment by chrisguttandin** [comment]
Thanks, for letting me know. I think it makes a lot of sense to handle this in a central place as well.

**Pull request closed without merging**
