### PR TITLE
Fix/1405

### LINKED ISSUE #1405: [create hint] EventEmitter warning + script never ends on macOS and node 10+
Node: v10.10.0
npm: 6.4.1
hint: v3.4.10

```sh
$ npm create hint

npx: installed 1 in 1.18s
? Is this a package with multiple hints? (yes) No
? What's the name of this new hint? tmp
? What's the description of this new hint 'tmp'? ...
? Please select the category of this new hint: development
? Please select the category of use case: (Use arrow keys)
❯ DOM 
? Please select the category of use case: DOM
? What DOM element does the hint need access to? (div) (node:6037) Error: Possible EventEmitter memory leak detected. 11 keypress listeners added. Use emitter.setMaxListeners() to increase limit
? What DOM element does the hint need access to? div
? Please select the scope of this new hint: any
Creating new hint in /Users/alrra/server/4/hint-copyright
External files copied
Creating new hint in /Users/alrra/server/4/hint-copyright
External files copied

New hint copyright created in /Users/alrra/server/4/hint-copyright

--------------------------------------
----          How to use          ----
--------------------------------------
1. Go to the folder 'hint-copyright'.
2. Run 'npm run init' to install all the dependencies and build the project.
3. Run 'npm run hint -- https://YourUrl' to analyze you site.
```

Also at the end it never returns the prompt.

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

Fix #1405 

AppInsights was preventing the `create` packages to finish on macOS. This flushes any pending data.
Also AppInsights was causing an `EventEmitter` warning with `create-hint` on macOS and node 10+. This PR removes AppInsights from the package.

### CODE REVIEW

**Comment by sarvaje** [comment]
@molant don't you want any tracking in the `create-hint`?

**Comment by molant** [comment]
See https://github.com/webhintio/hint/issues/1405#issuecomment-447716390

**Comment by sarvaje** [comment]
But you are keeping the analytics in other "create" packages, shouldn't be all of them removed?

**Comment by molant** [comment]
The other create packages don't have the `EventEmitter` warning message. I believe is a compat issue between AppInsights and inquirer/rxjs. I'm willing to take out analytics from this package and rely on downloads from npm to track this (and maybe open an issue to try once a newer version of AppInsights is released?).

In any case, that's why I asked in that issue. If we are all in the same page then this PR can be merged. If not then we can still add the `sendPendingData` and investigate more but IMO it's not worth it.

**Comment by antross** [comment]
> Do you mind open it?

Done. https://github.com/webhintio/hint/issues/1590

**Pull request merged**
