### PR TITLE
Docs: Update CLA link and add it in PR template

### PR DESCRIPTION
**Pull request by davidlj95**
## Pull request checklist

Make sure you:

- [x] Signed the Contributor License Agreement (after creating PR)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- **N/A** Added/Updated related documentation.
- **N/A** Added/Updated related tests.

## Short description of the change(s)
- Update of https://github.com/webhintio/hint/pull/5691 with new link

After looking for the CLA in docs for my [first contribution](https://github.com/webhintio/hint/pull/5690) found out the only reference to it had a link that didn't work (domain doesn't exist). Fixing that link + adding a link in PR template so impatient contributors like me can browse the CLA whilst the CLA signing comment appears.

### CODE REVIEW

**Review by vidorteg — APPROVED** [review]
Thanks again! LGTM

**Comment by davidlj95** [comment]
> /azp run

praying

😛

**Comment by davidlj95** [comment]
> Unfortunately it is still failing CI. I think that because it is modifying an `.md` file the linter step (to be more specific `markdown-link-validator`) is failing. I need to take a closer look to the markdown-link-validator usage to fix this and I'll ping you again 😅

Yup, no problem at all! I'll take a look too if have some time to help a bit moar :)

**Comment by vidorteg** [comment]
well I was able to make it pass validation :). Thank you for the contribution.

**Comment by davidlj95** [comment]
> well I was able to make it pass validation :). Thank you for the contribution.

Awesome! Thanks to you and your perseverance ☺️

**Pull request merged**
