### PR TITLE
Build: Adding Microsoft Security DevOps to pipelines

### PR DESCRIPTION
**Pull request by johnemau**
## Pull request checklist
Make sure you:

- [x] Signed the Contributor License Agreement (after creating PR)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)
Note: This is a test run PR to see how the CI responses to azure-pipeline changes (I am new to Github Actions).

The goal is to implement Microsoft Security DevOps action for enhanced security analysis of the webhint codebase. This will help make webhint and webhint users more secure.

### CODE REVIEW

**Comment by johnemau** [comment]
I am new to github actions, how do I get this PR to run all the regular checks?

**Comment by antross** [comment]
It's also possible that CI is trying to be too smart since none of the files changed were in any of webhint's packages (I'd have to go double-check the rest of the config to be sure). You can try adding a throwaway comment somewhere to test that theory.

**Comment by johnemau** [comment]
Blocking bug preventing this PR from landing: https://github.com/microsoft/security-devops-action/issues/21

**Comment by johnemau** [comment]
Fix for the blocking bug has been found, reopening PR.

**Comment by johnemau** [comment]
Github is in a bad state and won't update the commit in this PR (even though the branch is up to date, so I am going to close this PR and open a new one.

**Pull request closed without merging**
