### PR TITLE
Fix: Fail fast for CSP errors in Firefox

### LINKED ISSUE #2708: [Bug] (Firefox-only) Fallback on pages where content scripts fail
# 🐛 Bug report

## Description

STR: Run WebHint on this page in Firefox. Other pages with CSP: https://dashboard.stripe.com/login , https://profiler.firefox.com/
AR: Audit never finishes and has to be canceled. _Browser Console_ throws 2 errors for `EvalError: call to eval() blocked by CSP`

This is not WebHint's fails CSP is incorrectly applied to content scripts in Firefox, tracked in [bug 1267027](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027). This issue also affects the Redux and React extension. I am sorry that this causes extra work for this extension as well :( .

While the root cause gets assigned, fixed and rides the trains; webhint should pro-actively detect the issue and fall back, avoiding the endless audit loop. An existing fallback is when WebHint runs on https://addons.mozilla.org/ , which prevent content script injection. The detection could try to eval from a content script – timing out on an expected return value to detect a CSP issue.

### PR DESCRIPTION
**Pull request by antross**
Fix #2708

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

### CODE REVIEW

**Comment by antross** [comment]
Screenshot of how this now fails. The difference is an error message (vs a timeout) that occurs within a second (vs three minutes).

image

**Comment by antross** [comment]
Test bundles:
* Chromium: [webhint-0.0.7.zip](https://github.com/webhintio/hint/files/3597939/webhint-0.0.7.zip)
* Firefox: [webhint-0.0.7.zip](https://github.com/webhintio/hint/files/3597940/webhint-0.0.7.zip)

**Comment by molant** [comment]
What do you think of pointing to the issue in bugtracker so more people can chime in 🙃

**Comment by antross** [comment]
> What do you think of pointing to the issue in bugtracker so more people can chime in 🙃

@molant Not sure I follow...

**Pull request merged**
