### PR TITLE
Fix 71

### LINKED ISSUE #71: All collectors should automatically download the same type of resources (scripts, styles, fonts, icons, etc.)
By default, the collectors will not request certain resources (e.g.: manifest file, all font files, etc.). 

Since quite a few rules will need to analyze those requests/resources, it wouldn't make sense to have every rule add custom code to request them, so we should add a helper to do that and notify the subscribed rules.

---

What we might want to request (incomplete list):

- <del>manifest file (`<link rel="manifest" href="site.webmanifest">`)</del>
- `rss` and `atom` files (`<link rel="alternate" ... href="...">`)
- font files (specified in `@font-face` rules)
- images specified in css files, manifest file, etc.
- video, audio, and subtitle files
- source map files (e.g.: `//# sourceMappingURL=example.js.map`)

### PR DESCRIPTION
**Pull request by molant**
Making sure that all collectors download what they have to (favicon, fonts, etc.).

**jsdom**
* [x] favicon.ico
* [x] ~~fonts~~

**cdp**
* [x] favicon.ico (it is not always downloaded)

**add tests in events**
* [ ] favicon.ico
* [ ] manifest

Fix #71

### CODE REVIEW

**Comment by sarvaje** [comment]
@molant this PR was merge? I can't see any of these changes in master

**Comment by alrra** [comment]
> this PR was merge?

No, it seems @molant just closed this PR.

**Comment by molant** [comment]
Don't know what I did 16 days ago. I don't remember closing any PR so it was definitely not intentional :(

**Comment by alrra** [comment]
> Don't know what I did 16 days ago. I don't remember closing any PR so it was definitely not intentional :(

@molant 🤗 

----

Since the original source of the PR has been deleted, this PR [cannot be reopen](https://user-images.githubusercontent.com/1223565/27886925-d397d2f4-61e6-11e7-8abd-ae6dc448cda6.png). :(

@sarvaje Do you urgently need this code? After I finish some of the stuff that I'm working on, I can try to see if I can recuperate this somehow.

**Comment by sarvaje** [comment]
I can make a pr with changes, I just wanted to be sure that this code should be in master hehehehe

**Pull request closed without merging**
