### PR TITLE
Docs: Add note about `defaultProfile` and chrome launcher issue

### PR DESCRIPTION
**Pull request by sarvaje**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

### CODE REVIEW

**Comment by alrra** [comment]
@sarvaje In the future, add `Fix <issue_number>` at the end of the commit. Thanks!

**Comment by sarvaje** [comment]
@alrra in this case it was intentionally, IMO, this doesn't fix the issue, just add a note in the documentation.

But you are right, most of the time I forgot to add it hehehe.

**Comment by alrra** [comment]
> this doesn't fix the issue

Yes and no. Practically, until a new version of `chrome-launcher` is released, there is nothing we can do about it in `webhint` except inform users about the limitation. 

---

@webhintio/core Feel free to reopen #773 if you think it's worth having it opened.

**Comment by sarvaje** [comment]
>Yes and no. Practically, until a new version of `chrome-launcher` is released, there is nothing we can do about it in `webhint` except inform users about the limitation. 

That's true :)

**Comment by molant** [comment]
> until a new version of `chrome-launcher` is released

Actually is more of a limitation of chrome. You need to launch it with a special parameter to enable the debugging protocol. If you run it normally the browser doesn't listen into any port. If the browser is already opened when you use `chrome-launcher` with the option to use the default profile then it will not be able to connect to it and thus the reason of time outs.

**Pull request closed without merging**
