### PR TITLE
Chore: Refactor location tests to match similar text

### PR DESCRIPTION
**Pull request by antross**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~Added/Updated related documentation.~
- [x] Added/Updated related tests.

## Short description of the change(s)

Makes it easier to write tests with correct location
information by allowing tests to provide substrings
representing where a report should occur.

Previously tests had hard-coded locations which were
prone to mistakes due to difficulty visualizing how
they aligned with the actual text in a file.

----

This is fully functional, but I've only updated the tests for two hints so far to make it easier to adjust for feedback. If we like the approach I can convert the rest of our existing test positions before merging.

Pending test updates:
* ~Fix positions in hint-html-checker tests~
* [x] Fix off-by-one issue in hint-amp-validator
* [x] Fix incorrect positions in hint-compat-api
* [x] Fix incorrect positions in hint-no-protocol-relative-urls

### CODE REVIEW

**Comment by molant** [comment]
Looks like things are passing everywhere except windows (`compat-api` as usual). @sarvaje can you take a look so we can merge?

**Comment by antross** [comment]
@molant If we like the approach, do we want to cut over more of the existing tests before merging this or leave that for a separate PR at a later date?

**Comment by molant** [comment]
I personally like the approach. While we are at it I'd rather migrate everything to use this in the same PR if it's not going to take too long.

**Comment by antross** [comment]
> While we are at it I'd rather migrate everything to use this in the same PR if it's not going to take too long.

I don't think it should since many of our tests don't currently test for location (and I won't touch those). I'll start migrating and see how it goes.

**Comment by antross** [comment]
@sarvaje This is ready for review if you have time.

**Pull request merged**
