### PR TITLE
Chore: Enable tests on Windows CI

### LINKED ISSUE #2467: [Feature] Enable connector-puppeteer for Windows in CI [0.1]
This was disabled due to an issue with an old version of Chrome on the Windows instances in Azure Pipelines. Once this is resolved it should be re-enabled.

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~Added/Updated related documentation.~~
- [x] Added/Updated related tests.

## Short description of the change(s)

Fix #2467

### CODE REVIEW

**Comment by molant** [comment]
So it looks like we still don't have the latest version of Chrome and that we can still not update Chrome via `choco install googlechrome`.

I'm going to leave this PR open so we can rebase from time to time and see if the problem is fixed as I got notified the other day that everybody should get the fix in a few weeks (they do staged releases).

**Comment by molant** [comment]
@antross we have now Chrome 74 installed in the hosts but cannot run `choco install googlechrome` so we have 2 options:

* Wait until that command works (supposedly [a fix is being roll out](https://developercommunity.visualstudio.com/comments/577895/view.html) but I wonder if it was already in the Chrome 74 update and it is still not working.
* Remove the manual update of Chrome in this code (Windows builds will be the only ones that do not auto update) and maybe try next time `puppeteer` breaks because we don't have a supported browser.

Thoughts?

**Comment by antross** [comment]
> * Wait until that command works (supposedly a fix is being roll out but I wonder if it was already in the Chrome 74 update and it is still not working.
> * Remove the manual update of Chrome in this code (Windows builds will be the only ones that do not auto update) and maybe try next time puppeteer breaks because we don't have a supported browser.

Is there a way we could wrap the command to just log a warning and continue if it fails? Otherwise I'm fine with removing it for now and letting the tests run in Windows until we have another problem.

**Comment by molant** [comment]
> Is there a way we could wrap the command to just log a warning and continue if it fails?

I guess something could be done. Don't know if I want to silence that failure hoping that it will get fixed in the future. Personally I prefer the option of removing the command.

**Comment by molant** [comment]
Even though GitHub reports is failing, all hosts are green!!

image

**Comment by antross** [comment]
@sarvaje Can you take a look at this one? I can update the PR if you have any feedback. Otherwise I'll merge it once you give the 👍

**Pull request merged**
