### PR TITLE
Update: Add manifest-icons to config-pwa

### LINKED ISSUE #2352: [Feature] Update `configuration-pwas` with `manifest-icons`
Now that `manifest-icons` is merged, we should update the `configuration-pwa` to have it.

@antross thoughts?

@shivangg want to take care of that?

### PR DESCRIPTION
**Pull request by shivangg**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [x] Added/Updated related documentation.
- [x] ~Added/Updated related tests.~

## Short description of the change(s)

Did the changes in the `index.json` and README but left `package.json` as the `manifest-icons` is not yet published.

Fixes #2352

### CODE REVIEW

**Comment by molant** [comment]
@shivangg you have to update the `package.json` and add
```json
"hint-manifest-icons": "^1.0.0"
```

And then run `yarn` from the root of the project. This way `yarn` will create a symlink and it will be found to be used locally for now and ready for when we do the next release.

**Comment by molant** [comment]
@shivangg also if you rebase from master the macOS build should work now 😊

**Comment by shivangg** [comment]
@molant `yarn` runs successfully but on running hint with `{
    "extends": ["progressive-web-apps"]
}
`, it fails to find `manifest-icons`. 


image

**Comment by molant** [comment]
What command are you using to run hint and from where are you doing it? This will only work from `packages/hint` using `yarn hint`

**Comment by shivangg** [comment]
@molant Yes, I ran it from `packages/hint` using `yarn hint`.

Also, I changed the name in the `package.json` of `hint-manifest-icons` from `@hint/hint-manifest-icons` to `hint-manifest-icons`

<details>
<summary>Details</summary>

```bash
 ~/Pesto/week9/hint/packages/hint ● yarn hint http://localhost:5000 --debug
yarn run v1.15.2
$ node dist/src/bin/hint http://localhost:5000 --debug
  hint:home:shivangg:Pesto:week9:hint:packages:utils:dist:src:app-insights Enabling Application Insights +0ms
  hint:home:shivangg:Pesto:week9:hint:packages:utils:dist:src:network:as-uri Adding valid target: http://localhost:5000/ +0ms
  hint:config:config-validator Validating configuration +0ms
  hint:config Composing configuration from extends +0ms
  hint:utils:resource-loader Searching progressive-web-apps… +0ms
  hint:utils:resource-loader Package @hint/configuration- not found +0ms
  hint:utils:resource-loader Package hint-configuration- not found +0ms
  hint:utils:resource-loader @hint/configuration-progressive-web-apps is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader progressive-web-apps found in @hint/configuration-progressive-web-apps +0ms
  hint:config:config-validator Validating configuration +10ms
  hint:config Composing configuration from extends +2ms
  hint:config overriding config settings with values provided via CLI +1ms
  hint:config Initializing ignored urls +4ms
  hint:utils:resource-loader Searching jsdom… +6ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +15ms
  hint:utils:resource-loader @hint/connector-jsdom is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader jsdom found in @hint/connector-jsdom +320ms
  hint:utils:resource-loader Searching apple-touch-icons… +3ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +2ms
  hint:utils:resource-loader @hint/hint-apple-touch-icons is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader apple-touch-icons found in @hint/hint-apple-touch-icons +4ms
  hint:utils:resource-loader Searching manifest-app-name… +0ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +2ms
  hint:utils:resource-loader @hint/hint-manifest-app-name is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader manifest-app-name found in @hint/hint-manifest-app-name +1ms
  hint:utils:resource-loader Searching manifest-exists… +0ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +1ms
  hint:utils:resource-loader @hint/hint-manifest-exists is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader manifest-exists found in @hint/hint-manifest-exists +0ms
  hint:utils:resource-loader Searching manifest-file-extension… +1ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +1ms
  hint:utils:resource-loader @hint/hint-manifest-file-extension is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader manifest-file-extension found in @hint/hint-manifest-file-extension +1ms
  hint:utils:resource-loader Searching manifest-icons… +0ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +1ms
  hint:utils:resource-loader @hint/hint-manifest-icons is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader Can't require @hint/hint-manifest-icons +0ms
  hint:utils:resource-loader webhint-hint-manifest-icons is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader Can't require webhint-hint-manifest-icons +1ms
  hint:utils:resource-loader /home/shivangg/Pesto/week9/hint/packages/utils/dist/src/lib/hints/manifest-icons/manifest-icons.js is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader Can't require /home/shivangg/Pesto/week9/hint/packages/utils/dist/src/lib/hints/manifest-icons/manifest-icons.js +0ms
  hint:utils:resource-loader /home/shivangg/Pesto/week9/hint/packages/hint is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader Resource manifest-icons not found +0ms
  hint:utils:resource-loader Searching manifest-is-valid… +0ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +1ms
  hint:utils:resource-loader @hint/hint-manifest-is-valid is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader manifest-is-valid found in @hint/hint-manifest-is-valid +3ms
  hint:utils:resource-loader Searching manifest… +0ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +1ms
  hint:utils:resource-loader @hint/parser-manifest is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader manifest found in @hint/parser-manifest +1ms
  hint:utils:resource-loader Searching html… +0ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +1ms
  hint:utils:resource-loader @hint/formatter-html is not a JSON file, trying to load it normally +1ms
  hint:utils:resource-loader html found in @hint/formatter-html +22ms
  hint:utils:resource-loader Searching summary… +0ms
  hint:utils:resource-loader Package hint-configuration-progressive-web-apps not found +1ms
  hint:utils:resource-loader @hint/formatter-summary is not a JSON file, trying to load it normally +0ms
  hint:utils:resource-loader summary found in @hint/formatter-summary +2ms
  hint:home:shivangg:Pesto:week9:hint:packages:utils:dist:src:app-insights Sending event "missing" to Application Insights with value ["hint-manifest-icons"] +2s
The following package is missing:
    hint-manifest-icons
There is a package from your .hintrc file not installed or with an incompatible version. Do you want us to try to install/update them? (Y/n)
```

</details>

**Comment by molant** [comment]
@shivangg I've downloaded your PR locally, added the missing line to `package.json`, built everything and it was working:

image


The `.hintrc` file was:
```json
{
  "extends": ["progressive-web-apps"]
}
```

And I run `yarn hint https://example.com`  from `/packages/hint`

I've pushed my very minor change but we should be ready to merge this anytime 😊

**Pull request merged**
