### PR TITLE
New: Improve error messages when running tests

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~Added/Updated related documentation.~~
- ~~Added/Updated related tests.~~

## Short description of the change(s)

When validating a report `hint-runner` checked all the properties at the
same time. This made difficult to debug what property was not matching,
and what was the expected value.

Now `hint-runner` provides more information for each of the properties
that validates, and comparing to the closest matched report.

Old behavior:

image

New behavior:

image

### CODE REVIEW

**Comment by molant** [comment]
The current error is because in apple-touch-icons we have 2 reports that are exactly the same (they only have the message). I think we should add a location to both of them and in general try to avoid that scenario.

@antross what do you think?

**Comment by antross** [comment]
> The current error is because in apple-touch-icons we have 2 reports that are exactly the same (they only have the message). I think we should add a location to both of them and in general try to avoid that scenario.
> 
> @antross what do you think?

SGTM

**Comment by molant** [comment]
`no-broken-links` fails because it has duplicate reports.
We haven't done any progress on pointing to attributes so not sure how to fix this. Maybe have some code at the end in `hint-test-runner` that checks that all the filtered messages are the same and validate everything (but we will have to remove them from the list similarly to what was done before).

**Comment by molant** [comment]
@sarvaje this should be ready for another review

**Comment by sarvaje** [comment]
LGTM if the tests pass we can merge it!

**Pull request merged**
