### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by coliff**
images are optimized losslessly with ImgBot.

Your image file size has been reduced by **17%** 🎉

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /packages/formatter-excel/images/summary.png | 5.77kb | 4.36kb | 24.33% |
| /packages/hint-manifest-icons/tests/fixtures/icon-192x192.png | 1.92kb | 1.50kb | 21.62% |
| /packages/hint-performance-budget/tests/fixtures/image.png | 362.29kb | 284.40kb | 21.50% |
| /packages/hint-image-optimization-cloudinary/tests/fixtures/nellie-studying.png | 280.51kb | 236.79kb | 15.58% |
| /packages/formatter-excel/images/details.png | 27.25kb | 23.83kb | 12.53% |
| /packages/hint-manifest-icons/tests/fixtures/icon-128x128.png | 1.17kb | 1.10kb | 6.08% |
| /packages/hint-manifest-icons/tests/fixtures/icon-512x512.png | 25.15kb | 24.30kb | 3.38% |
| /packages/hint/docs/user-guide/configuring-webhint/images/default-config.png | 36.20kb | 35.74kb | 1.29% |
| | | | |
| **Total :** | **740.25kb** | **612.03kb** | **17.32%** |

### CODE REVIEW

**Comment by coliff** [comment]
strange. says CLA not signed yet, but clicking on the link says it is signed.

image

**Comment by molant** [comment]
I believe it's the bot who needs to sign the CLA.

I'll reach out to the foundation so they added to the pre-approved list.

Thanks!


________________________________

**Comment by molant** [comment]
@coliff an alternative will be to modify the last commit and make you the commiter.
Also there are a few files that should not be changed as we are using them for some of the perf hints.
Can you please revert back the changes for 

```
/packages/hint-performance-budget/tests/fixtures/image.png
/packages/hint-image-optimization-cloudinary/tests/fixtures/nellie-studying.png
```

Thank you!

**Comment by jorydotcom** [comment]
I've confirmed that the bot has 'signed' the CLA and that's in our database - I'm not sure why it posted twice, but I suspect it has to do with the JSF's CLA-Assistant instance (it's in proper need of an update). An owner of the Org should be able to merge the PR in regardless.

**Comment by molant** [comment]
Thanks @coliff

**Pull request merged**
