### PR TITLE
Breaking: Raise min required node version to 14

### PR DESCRIPTION
**Pull request by antross**
## Pull request checklist

Make sure you:

- [x] Signed the Contributor License Agreement (after creating PR)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

Align specified minimum node version with that required by recent dependency updates.

### CODE REVIEW

**Review by sarvaje — APPROVED** [review]

**Comment by molant** [comment]
what do you think about making the minimum version 14 given that 12 will no longer be maintained in a handfull of months and the recommendation is to move already?
Otherwise there should be another breaking soon-ish

| RELEASE | STATUS          | CODENAME | INITIAL RELEASE | ACTIVE LTS START | MAINTENANCE LTS START | END-OF-LIFE |
| ------- | --------------- | -------- | --------------- | ---------------- | --------------------- | ----------- |
| v12     | Maintenance LTS | Erbium   | 2019-04-23      | 2019-10-21       | 2020-11-30            | 2022-04-30  |
| v14     | Maintenance LTS | Fermium  | 2020-04-21      | 2020-10-27       | 2021-10-19            | 2023-04-30  |
| v16     | Active LTS      | Gallium  | 2021-04-20      | 2021-10-26       | 2022-10-18            | 2024-04-30  |
| v17     | Current         |          | 2021-10-19      |                  | 2022-04-01            | 2022-06-01  |
| v18     | Pending         |          | 2022-04-19      | 2022-10-25       | 2023-10-18            | 2025-04-30  |

**Comment by antross** [comment]
@molant I'd rather not move beyond 12 until it's no longer being maintained. Another breaking change in 5.5 months seems reasonable.

**Comment by molant** [comment]
@antros v6.0.0 was released in Dec 2, 2019. That's almost 2 years ago.
Given the trends, node recommendations, and the frequency of the project's breaking changes I think it makes more sense to bump to v14 directly.

**Comment by antross** [comment]
Marking as blocked until we're ready to do a major version bump. (Will also need to update CI to run Node 14, but we are planning to do that sooner, separately).

**Review by vidorteg — APPROVED** [review]
LGTM

**Comment by antross** [comment]
@molant I think it's time to merge this and put out a new major version since Node 12 has reached end-of-life. Any further comments/feedback or are you good with this moving forward?

**Comment by molant** [comment]
No concerns from my side!

**Pull request merged**
