### PR TITLE
Chore: Refactor to prepare for i18n

### LINKED ISSUE #1776: Make extension-browser UI localizable
Move strings to a JSON file and resolve them via a function call.

### PR DESCRIPTION
**Pull request by antross**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~Added/Updated related documentation.~
- ~Added/Updated related tests.~

## Short description of the change(s)

Fix #1776 

Bundle for testing:
* [extension-browser-pr-1848.zip](https://github.com/webhintio/hint/files/2842984/extension-browser-pr-1848.zip)

Of interest, I typed `getMessages` using a script that generates a type for allowed strings based on what's defined in `messages.json`. This ensures we always reference a string that actually exists.

### CODE REVIEW

**Comment by molant** [comment]
> This ensures we always reference a string that actually exists.

Nice! This is looking good!

**Comment by antross** [comment]
This is now ready for full review. 

It covers everything *except* the names of the hints and the messages generated by those hints. This is because those are imported from outside of the extension and currently being evaluated in #1775.

**Comment by molant** [comment]
@antross there seems to be some type errors in your PR from what I'm seeing in CI. Can you please fix them?

**Comment by antross** [comment]
@molant any chance there's a difference in `typescript` versions in CI versus local? The type assignment I'm doing is working locally with TypeScript 3.3.1, but is failing in CI:
```
error TS2345: Argument of type 'Category' is not assignable to parameter of type 'MessageName'.
```

Yet `MessageName` is a superset of `Category` so the assignment should pass 🤔

**Comment by molant** [comment]
It should be using the same version. I've requeued the build. If it continues failing we can dig deeper (`npm` vs `yarn` or a dependency that hasn't been built or something like that?)

**Comment by molant** [comment]
This is still failing and I cannot repro locally. I don't see the warning message I get about using TypeScript 3.3.1 when running locally:

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: ~3.2.1

YOUR TYPESCRIPT VERSION: 3.3.1

Please only submit bug reports when using the officially supported version.

=============
```

So maybe we are installing an older version somehow (I haven't found any package using an old version though 🤔).

**Comment by molant** [comment]
This is still failing after rebasing with master with the changes of TypeScript. We might want to add an extra step in the build process to print the versions of all the things we are using (node, npm , yarn, typescript) in general to have a bit more information in general about the environment.

**Comment by antross** [comment]
@molant I deleted my `node_modules` folder, re-ran `yarn`, and can now repro this locally. Investigating...

**Comment by antross** [comment]
I think I figured out what happened - I had a stale local copy of the `Categories` enum which failed to break when "Pitfalls" was added after a rebase, but CI correctly caught this. Not sure why my local copy didn't get rebuilt, but I added "Pitfalls" to `messages.json` for localization and the error went away. Here's hoping CI agrees 🤞

**Pull request merged**
