### PR TITLE
fix: Update moduleResolution options

### LINKED ISSUE #5719: [Bug] `Bundler` is not a valid `moduleResolution` option in tsconfig
# 🐞 Bug report

## Description

The tsconfig parser's `moduleResolution` options are missing `Bundler` as a valid strategy.  I came across this bug while using the Microsoft Edge Dev Tools extension in vscode; `bundler` was incorrectly flagged as invalid.
## Details
webhint v2.1.11
Pop OS
Microsoft Edge Tools for VS Code

### PR DESCRIPTION
**Pull request by bmc1995**
## Pull request checklist

Make sure you:

- [x] Signed the Contributor License Agreement (after creating PR)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)
Adds `Bundler` as a valid `moduleResolution` strategy 

from [typescriptlang.org](https://www.typescriptlang.org/tsconfig#moduleResolution):
>'bundler' for use with bundlers. Like node16 and nodenext, this mode supports package.json "imports" and "exports", but unlike the Node.js resolution modes, bundler never requires file extensions on relative paths in imports.

resolves #5719

### CODE REVIEW

**Comment by gracefullight** [comment]
Is there any chance to merge this PR?

**Review by nikkehtine — APPROVED** [review]

**Review by hamirmahal — COMMENTED** [review]
#5736 might duplicate this.

**Comment by Ruslanmsv** [comment]
@vidorteg Can it be approved please?

**Review by vidorteg — APPROVED** [review]
Sorry for the slow reply on this, I have been really busy lately. But I appreciate your contribution to the webhint project. LGTM

**Pull request merged**
