### PR TITLE
Docs: Update readme and docs with missing information

### PR DESCRIPTION
**Pull request by jaspreet57**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~[ ] Added/Updated related documentation.~~
- ~~[ ] Added/Updated related tests.~~

## Short description of the change(s)
Updating some missing information found while going through docs. Like:
* Add new categories of hint - development and pitfalls
* Typo fixes
* Fix broken links in FAQ

### CODE REVIEW

**Comment by jaspreet57** [comment]
@antross This build fails for `macOS` for some reason. Which seems to be 'not able to update google-chrome'.

logs from azure build:
```sh
...
...
libggz
libguess
lysp
==> Satisfying dependencies
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
Error: Checksum for Cask 'google-chrome' does not match.
Expected: cceb02b5d2e8d7b2d5d3e009982e8c1ca1a50419702f5f74643b86d236ff9c62
  Actual: 5a4ad06d569ec50edc53c0a864df681bd9f8d9c8b183515e583d7f036908b55a
    File: /Users/vsts/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
==> Verifying SHA-256 checksum for Cask 'google-chrome'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
##[error]Bash exited with code '1'.
##[section]Finishing: Update Chrome on macOS
```

It says to remove `chrome.dmg` file to proceed install. Please let me know if it is known issue or something I changed in this PR.

**Comment by antross** [comment]
@jaspreet57 Yes, this step is known to occasionally fail. You can ignore it.

**Comment by jaspreet57** [comment]
> @jaspreet57 Yes, this step is known to occasionally fail. You can ignore it.

OK

**Comment by antross** [comment]
@sarvaje Can you take a quick look so we can merge this? Thanks!

**Pull request merged**
