### PR TITLE
Fix: Updating the user-agent in the requester.

### LINKED ISSUE #5258: [Bug] Update User-Agent inside request.ts
# 🐞 Bug report

## Description

User-Agent inside
[packages/utils-connector-tools/src/requester.ts]

needs to be updated. It currently points to 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

## Details

packages/utils-connector-tools

### PR DESCRIPTION
**Pull request by vidorteg**
## Pull request checklist

Make sure you:

- [x] Signed the Contributor License Agreement (after creating PR)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [x] Added/Updated related documentation.
- [x] Added/Updated related tests.

## Short description of the change(s)
Updates the `user-agent` for the `requester` class.

------
Fix #5258

### CODE REVIEW

**Review by flynnolivia — APPROVED** [review]
LGTM! Do you know how often this needs to be updated?

**Comment by vidorteg** [comment]
> LGTM! Do you know how often this needs to be updated?

There is no need to keep this updated to the last version, but when doing the 'replace request' work we spotted it and thought it would be a good idea to update it as it was falling behind (around ~30 versions ATM)

**Review by hkal — APPROVED** [review]
LGTM

**Pull request merged**
