### PR TITLE
New: Add publishing scripts for OVSX

### PR DESCRIPTION
**Pull request by entepe85**
## Pull request checklist

Make sure you:

- [X] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [X] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

### CODE REVIEW

**Comment by entepe85** [comment]
This is quite curious. I signed the CLA and added my company email to my account.

**Comment by molant** [comment]
> This is quite curious. I signed the CLA and added my company email to my account.

You might want to make sure the commit is with your personal account and maybe redo the PR?

@sarvaje had a similar issue the other day IIRC.

**Comment by entepe85** [comment]
Seems like GitHub does recognize the commit coming from the right account.

grafik

If I follow the link to sign the CLA, it is shown as already signed.

**Comment by molant** [comment]
> And I totally forgot to comment on the PR: Authentication on Open VSX requires to log into open-vsx.org through GitHub and then creating an access token which is needed for the publishing to succeed

Yup, already did that and claimed the org, need to figure out now how I can add more people to the org because @johnemau is probably the next one doing a release...

I've pushed a new commit to your PR that fixes some linting errors. Waiting for CI to pass although should be fine.

Thanks a lot!

**Pull request merged**
