### PR TITLE
Fix: Missing dependencies

### LINKED ISSUE #2115: [Bug] Formatters have missing dependencies [0.1]
`strip-ansi` is missing from a few formatters or marked as a `devDependency`

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~Added/Updated related documentation.~~
- ~~Added/Updated related tests.~~

## Short description of the change(s)

Fix #2115

### CODE REVIEW

**Comment by sarvaje** [comment]
@molant I'm taking a look to the dependencies, can you keep this PR open until I finish and add/move things when I found them?

**Comment by sarvaje** [comment]
Tasks:

| Action | Package | Dependency(ies) | Done |
|-----|-----|-----|-----|
| Move | connector-chrome -> utils-debugging-protocol-common | lockfile, @types/lockfile |  |

**Comment by molant** [comment]
@sarvaje sure. I'm working on a script to validate dependencies so this will be a good test run 😊

**Comment by molant** [comment]
@sarvaje let me know when you are done!

**Comment by sarvaje** [comment]
@molant ready!

**Comment by molant** [comment]
@sarvaje you say to delete `@hint/connector-jsdom` in `utils-tests-helpers`, why? It's being used same as the `chrome` one 🤔

**Comment by sarvaje** [comment]
> @sarvaje you say to delete @hint/connector-jsdom in utils-tests-helpers, why? It's being used same as the chrome one

Ups, I meant @hint/connector-local

**Comment by molant** [comment]
Closing in favor of #2131

**Pull request closed without merging**
