### PR TITLE
Fix: Syntax highlighting color incorrect for Edge

### LINKED ISSUE #3270: [Bug] Syntax highlighting colors are incorrect for Edge in light theme
Actual:
image

Expected (align with Elements panel):
image

Thanks @ststimac for pointing this out!

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #3270

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

Here are the extensions for self hosting:

Chromium:
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3853641/webhint-1.2.1.zip)

Firefox:
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3853642/webhint-1.2.1.zip)

### CODE REVIEW

**Comment by sarvaje** [comment]
This is how it looks for light schema:
image

**Comment by sarvaje** [comment]
I'm going to take a look to the dark theme before remove the draft

**Comment by sarvaje** [comment]
Dark theme screenshot:

image

**Comment by molant** [comment]
@hxlnt @ststimac can you please take a look at this PR?

**Comment by hxlnt** [comment]
Some of the quotemarks and triangle brackets aren't what I would expect. Namely, the triangle brackets and the last set of equal sign/quotemarks for style, which seem to be light blue.

Compare against VS Code:

image

This applies to the light theme as well.

**Comment by molant** [comment]
> Namely, the triangle brackets and the last set of equal sign/quotemarks for style, which seem to be light blue.

@hxlnt but that's how they look in the DevTools 🤔

image

**Comment by hxlnt** [comment]
> > Namely, the triangle brackets and the last set of equal sign/quotemarks for style, which seem to be light blue.
> 
> @hxlnt but that's how they look in the DevTools 🤔
> 
> image

I don't feel strongly about the triangle bracket difference, but the last equals sign and quotemark being blue where all the others are black looks like a bug. Not seeing this behavior in DevTools.

**Comment by hxlnt** [comment]
image

(Adding a screenshot for clarity--these should be black, I think, rather than blue to match the other quotemarks and equal signs.)

**Comment by sarvaje** [comment]
ahhhh, now I see what you say, that is a bug

**Comment by molant** [comment]
These are screenshots from all platforms

|          | Image |
| ------| ----------|
| Edge | image |
| VS Code | image |
| webhint | image |

 Triangle bracket and initial quotes seem to be consistent with Edge DevTools

**Comment by sarvaje** [comment]
I have fixed the quotes for the styles attribute, this is how it looks now:
image

image

Good catch @hxlnt.

**Comment by sarvaje** [comment]
Here are the extensions for self hosting:

Chromium:
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3853641/webhint-1.2.1.zip)

Firefox:
[webhint-1.2.1.zip](https://github.com/webhintio/hint/files/3853642/webhint-1.2.1.zip)

**Pull request merged**
