### PR TITLE
Fix: Deprecate `connector-chrome`

### LINKED ISSUE #2814: Deprecate connector-chrome in favor of connector-puppeteer
Yes, `@hint/connector-puppeteer` is intended to replace `@hint/connector-chrome` and nobody should write new code referencing the latter. Now that we've switched to `@hint/connector-puppeteer` as the default, we should be able to even mark the `@hint/connector-chrome` package as deprecated.

_Originally posted by @antross in https://github.com/webhintio/hint/pull/2782#issuecomment-520878947_

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~Added/Updated related documentation.~~
- ~~Added/Updated related tests.~~

## Short description of the change(s)

Once merged we should run

Fix #2814

```
npm deprecate @hint/connector-chrome@"<= 4.0.9" "@hint/connector-chrome is obsolete, please use @hint/connector-puppeteer"

npm deprecate @hint/utils-debugging-protocol-common@"<= 4.0.9" "@hint/connector-chrome is obsolete, please use @hint/connector-puppeteer"
```

### CODE REVIEW

**Comment by molant** [comment]
This is ready for another review

**Comment by molant** [comment]
> One question: what do we need to do to mark the existing packages as deprecated on npm?

Being good citizens. We no longer maintain them, the code has been removed and they should migrate to newer versions. They will get a message telling them what they should be using instead and that could help save time to developers trying to figure out why a package hasn't been updated in years 😉

**Comment by antross** [comment]
@molant I think you misunderstood my question. *How* do we mark them as deprecated?

**Comment by molant** [comment]
The command is in the first comment 😊


________________________________

**Comment by antross** [comment]
😂 That's what I get for skipping straight to the code - thx

**Comment by molant** [comment]
I've run the deprecation commands.

**Pull request merged**
