### PR TITLE
Fix: UserConfig type not exported by hint

### PR DESCRIPTION
**Pull request by QmarkC**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

Fix missing `UserConfig` type from hint (#3952) by adding `export type { UserConfig } from '@hint/utils';` to the analyzer types.

### CODE REVIEW

**Comment by antross** [comment]
I'll merge once this passes CI. 

Just a heads-up that we may not get a release out with this change until sometime next week. In the meantime I suspect you already know importing the type directly from `@hint/utils` is fine even in external code (though we much prefer to make this available directly from the `hint` package so thanks again for the fix!)

**Comment by QmarkC** [comment]
> I'll merge once this passes CI.

The Linux check is failing due to bundle size lint on the browser extension package. Should I add a commit to bump that?

```
Error: Bundle size of 691KB exceeds limit of 690KB defined in package.json
```

**Comment by antross** [comment]
No need. I just bumped it in another PR that just merged (related to a TypeScript upgrade). I'll rerun CI and see if that takes care of it.

**Pull request merged**
