### PR TITLE
Fix: Using `formatter-stylish` in CI by default.

### LINKED ISSUE #2892: [Feature] Improve logging in CI
Right now, we are using `formatter-summary` by default for the configurations. This formatter only says what "needs to be fixed" but not where.

During today's retrospective we agree that we should give more information by default in CI.

Even if the user is able to use its own configuration, the idea is to offer to the user more information by default.

To achieve this we have at least two options:

1. Check if we are in CI and set by default another formatter like `stylish`.
1. Modify the configurations to use `stylish` instead of `summary`.

I'm saying `stylish` but we can use any other. (But I prefer stylish :P)

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #2892

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

### CODE REVIEW

**Comment by molant** [comment]
@antross can you please open an issue to discuss that? Probably part of the next version discussion we should have.

**Comment by antross** [comment]
@sarvaje want to add the test case @molant suggested so we can unblock and merge this PR?

**Comment by sarvaje** [comment]
ok

**Comment by sarvaje** [comment]
I'm taking a look to the code and that test case is already there:
https://github.com/webhintio/hint/pull/2893/files#diff-41369f12d00e1d73e14241156907f6ffR207
https://github.com/webhintio/hint/pull/2893/files#diff-41369f12d00e1d73e14241156907f6ffR207

**Comment by antross** [comment]
@sarvaje maybe I'm missing something, but I don't see a test that validates it only uses `html` and `summary` when *NOT* in CI...

**Comment by sarvaje** [comment]
no literally, but we are checking that the configuration is { extends: ["web-recommended"]} and {extends: ["development"]}

**Comment by molant** [comment]
It's weird to me that we have a test to check the formatters in one environment and not another.

**Comment by sarvaje** [comment]
The test is there, if it is not CI, the configuration is { extends: ["web-recommended"]} if it is in CI, the configuration is {extends: ["web-recommended"], formatters: ["stylish", "html"]}

If we are not in CI, the property formatter is not initialized and we are using whatever comes from the extends.

**Comment by sarvaje** [comment]
I can't check the property formatter, because when I'm not in CI, I only use the extends. And I don't think we should test here what the extends has by default.

**Comment by molant** [comment]
OK, then 👍

**Pull request merged**
