### PR TITLE
Fix: Generated file `browser-compat-api` incomplete

### LINKED ISSUE #3901: [Bug] Generated file `browser-compat-data.ts` doesn't contains the mdn_url for most of the html element
To be able to generate a link to the documentation in `hint-compat-api`, we need the mdn documentation link for css and html elements.

Most of the html elements don't have that link

### PR DESCRIPTION
**Pull request by sarvaje**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

This commit add the property mdn_url for all the html elements.
Additionally, as a side effect, a bug was found in the generation
of this file, and now the file size is smaller.

Fix #3901

### CODE REVIEW

**Comment by molant** [comment]
@sarvaje CI keeps failing even after restart. Can you please take a look?

**Comment by sarvaje** [comment]
> @sarvaje CI keeps failing even after restart. Can you please take a look?

Yep

**Comment by sarvaje** [comment]
CI should be fixed now! Thanks @antross!!

**Pull request merged**
