### PR TITLE
Docs: Update CLA link and add it to PR template

### PR DESCRIPTION
**Pull request by davidlj95**
## Pull request checklist

Make sure you:

- [x] Signed the Contributor License Agreement (after creating PR)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- **N/A** Added/Updated related documentation.
- **N/A** Added/Updated related tests.

## Short description of the change(s)
After looking for the CLA in docs for my [first contribution](https://github.com/webhintio/hint/pull/5690) found out the only reference to it had a link that didn't work (domain doesn't exist). Fixing that link + adding a link in PR template so impatient contributors like me can browse the CLA whilst the CLA signing comment appears.

### CODE REVIEW

**Comment by vidorteg** [comment]
[Doing some cleaning]. Unfortunately and due to me missing to review  this 😓the proposed url has gone also stalled. feel free to reopen pointing to the new one, or I can also do it if needed. thanks again for the contribution and sorry that this went missed.

**Comment by davidlj95** [comment]
No problem at all @vidorteg :) just reopened with new link here: https://github.com/webhintio/hint/pull/5751

**Pull request closed without merging**
