### PR TITLE
Fix: Refactor for file name convention

### LINKED ISSUE #1748: [Bug] Not all file names follow the same convention
# 🐛 Bug report

## Description

All files should be lower case and dash separated. There are some that don't follow this convention such as `fetchContent.ts` in `connector-chrome`.

### PR DESCRIPTION
**Pull request by karansapolia**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~Added/Updated related documentation.~~
- [x] Added/Updated related tests.

## Short description of the change(s)
Rename files which do not follow naming convention of
lower case dash seperated file names. Update all references
changed file names.

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fix #1748

### CODE REVIEW

**Comment by molant** [comment]
@karansapolia I plan on merging this as soon as we resolve some issues we are having with TypeScript with some of the other PRs. If there are any conflicts after we merge those I'll take care of them.

Thanks again!

**Comment by molant** [comment]
I've rebased with the latest `master`. If everything goes well I'll merge tomorrow morning!

**Comment by karansapolia** [comment]
Yay! 😊🤞🏻

**Comment by molant** [comment]
For whatever reason GitHub is not linking to the right results. The correct ones are https://dev.azure.com/webhint/webhint/_build/results?buildId=1608 and all are green:
image

**Comment by molant** [comment]
Congratulations in your first merged PR @karansapolia 🎉

**Comment by karansapolia** [comment]
Thank you so much! You have been very supportive! Looking forward to many more PRs 😃😋

**Pull request merged**
