### PR TITLE
Flatten utils

### PR DESCRIPTION
**Pull request by antross**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

Opening as a draft as actually flattening the exported utils was easy (first commit), but I haven't finished updating all the references yet since they couldn't be easily touched by a regex (progress in second commit).

Worth getting feedback on if we're happy with how this flattened out before I finish updating references anyway.

### CODE REVIEW

**Comment by sarvaje** [comment]
This PR looks good, I thing you can remove it from draft.

**Comment by antross** [comment]
@molant @sarvaje Also, I didn't flatten a few things like `appInsights` or `npm` which were implemented as single files as opposed to sub-folders. Still, I could see those being included as well (potentially with a rename or two to make the APIs clearer in a flattened world). What do you think?

**Comment by molant** [comment]
>  I could see those being included as well 

Sounds good. We should probably rethink the analytics part in case we need to implement multiple providers and have some abstraction?

**Comment by antross** [comment]
Abandoning this PR as we're going to revisit this in a non-breaking way (supporting both flattened and unflattened imports).

**Pull request closed without merging**
