### PR TITLE
Fix/timeouts

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~Added/Updated related documentation.~~
- ~~Added/Updated related tests.~~

## Short description of the change(s)

I'm trying to figure out why Travis timesout after merging https://github.com/webhintio/hint/commit/ea56a95ce452c136c872dadd9c790b2cc5f9cd06.

For that I'll split all changes in different commits and see what is the culprit.

### CODE REVIEW

**Comment by sarvaje** [comment]
@molant, I think you need to rebase this.

**Comment by molant** [comment]
> I think you need to rebase this.

Nope, I've removed the commit and adding them one by one. [Travis is building them in my fork](https://travis-ci.org/molant/hint).

**Comment by sarvaje** [comment]
but you have conflicts XD

**Comment by molant** [comment]
This should be ready. I've changed the history removing the previous CDP changes and @alrra's commit changing the parser tests. I've also split the commits in multiple to make it easier to see what is going on.

Ideally this should be forced pushed into master. I don't think anything has been added since I branched.

**Comment by molant** [comment]
For the curious, this is the travis run in my branch: https://travis-ci.org/molant/hint/builds/431682392

**Comment by molant** [comment]
@alrra, I'm almost sure the timeouts we are having right now are because travis is using the latest npm version that still has the base64 error. Locally they are passing.

**Comment by alrra** [comment]
@molant I cannot make this work locally. :(

---

Until we figure this out, I [reverted](https://github.com/webhintio/hint/commit/85496fe75f0ec9995a6bded7058881cedca556eb) the changes.

**Comment by molant** [comment]
Are you getting timeouts or something different locally?

**Comment by alrra** [comment]
> Are you getting timeouts or something different locally?

timeouts

**Comment by molant** [comment]
Closing in favor of https://github.com/webhintio/hint/pull/1337

**Pull request closed without merging**
