### PR TITLE
Chore: Return real promises in no-broken-links#createReports

### LINKED ISSUE #2034: [Feature] `no-broken-links#createReports` should return only real promises in the array instead of `Promise.resolve()`
With the changes in #1943 there's a lot of code in `createReports` that returns `Promise.resolve()`. We should return only real Promises instead of doing that.
For that we could change `return urls.map((url) => {` to something like:

```ts
const requests: Promise<void>[] = [];
urls.forEach((url) => {
// magic here
requests.push(realPromiseToAdd);
}

return requests;
```

### PR DESCRIPTION
**Pull request by jnv**
Fix #2034

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

In `no-broken-links` hint use `for..of` loop for collecting requests in `createReports` function which return "real" promises instead of unrelated `Promise.resolve()`.

### CODE REVIEW

**Comment by sarvaje** [comment]
What are the benefits of this change (I like it, but I'm curious)

**Comment by jnv** [comment]
> What are the benefits of this change? (I like it, but I'm curious)

Well, I have just followed #2034 so @molant can give better explanation. From my point of view there are at least two benefits:

- The returned promises are actually connected to the requests being made so awaiting them makes more sense,
- you are returning only promises for requests which were actually fired (while previously all incoming URLs were mapped to empty promises).

(Also despite the original recommendation I opted for `for..of` which tends to give better performance than `forEach`, but I don't insist on that.)

**Comment by sarvaje** [comment]
Cool! Thanks for the PR. I also like the `for..of` more than `forEach`.

**Review by sarvaje — APPROVED** [review]

**Comment by jnv** [comment]
Looks like the macOS CI got stuck? 🤔

**Comment by sarvaje** [comment]
> Looks like the macOS CI got stuck?

Yep, it timed out, but for some reason, didn't report an error... It should be running now

**Pull request merged**
