### PR TITLE
New: Add pitfalls icon

### PR DESCRIPTION
**Pull request by ststimac**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [x] Added/Updated related documentation.
- [x] Added/Updated related tests.

## Short description of the change(s)

Add pitfalls icon

### CODE REVIEW

**Comment by molant** [comment]
@sarvaje @antross I think we should add the pitfalls category directly on this PR (#1840) 

* [ ] Update category to code
* [ ] Move certain hints to this category
* [ ] Update HTML formatter

What do you think?

**Comment by molant** [comment]
This is ready for review.
Before merging we should add a description to the category in https://github.com/webhintio/webhint.io/blob/1ccbde17837af1619038540abc715b4bd5c81fba/_config.yml#L112

@antross want to think about it?

**Comment by antross** [comment]
Yep: https://github.com/webhintio/webhint.io/pull/627

Unless anyone wants to tweak anything a bit, it should be good to merge.

**Comment by molant** [comment]
I think we need to rework the commits and their messages. What do you think of:

* Combine 3e66b98b65487fdec1b249d43938359a76bc830d,  520d2c1a650528eaec645a0ceeadbb6d91ed720d and aa44fe0571b5cdec32d877e6e6904bbc6378abbf --> New: Add category `pitfalls`
* 8073bb578fefec8dc5713fc62fd83ae2be3bbc4f --> Breaking: Change category to `pitfalls`

**Comment by sarvaje** [comment]
> I think we need to rework the commits and their messages. What do you think of:

it is ok for me. Do you want me to do it?

**Comment by molant** [comment]
> Do you want me to do it?

Yes please

**Pull request merged**
